--MASTERS - JOSH ALFORD PROVIDES FILE FROM FINANCE TEAM

--MHS SSM - ERIN HUGHES SEND MONTHLY EMAIL WITH EXCEL FILE

--CPH SSM - PULLED FROM DASHBOARD

USE ROLE SBX_EA_GENERAL_FR;
USE SECONDARY ROLE ALL;

--6. MHS ISAM
--MHS ISAM CUSTOMER COUNT
CREATE OR REPLACE TEMPORARY TABLE MHS_ISAM_CUST AS
--SELECT * FROM MHS_ISAM_CUST

SELECT  VW_REP_HIERARCHY.CUST_ACCT_ID,
        REP_NAME,
        SLS_TERR_ID,
        CASE 
        WHEN SLS_TERR_ID IN ('0761','1132','1133','7898','7988','7995','7996','7997') THEN 'TERR_ONE'
        WHEN SLS_TERR_ID IN ('7881','7891','7892') THEN 'TERR_TWO'
        WHEN SLS_TERR_ID IN ('7989','7992','7994','7998') THEN 'TERR_THREE' 
        ELSE 'OTHER' END AS TERR_GRP
FROM    PRD_PSAS_ANALYTICS_DB.GOLD_CRM.VW_REP_HIERARCHY
WHERE   REP_GRP_NAME = 'INSIDE SALES TEAM'
AND     BUS_SGMNT = 'MHS'
AND     ROLE_TYPE = 'ISAM'
AND     CURRENT_RECORD_IND = 'Y'
GROUP BY  VW_REP_HIERARCHY.CUST_ACCT_ID,
        SLS_TERR_ID,
        REP_NAME,
        CASE 
        WHEN SLS_TERR_ID IN ('0761','1132','1133','7898','7988','7995','7996','7997') THEN 'TERR_ONE'
        WHEN SLS_TERR_ID IN ('7881','7891','7892') THEN 'TERR_TWO'
        WHEN SLS_TERR_ID IN ('7989','7992','7994','7998') THEN 'TERR_THREE' 
        ELSE 'OTHER' END;         


--MHS ISAM CUSTOMER COUNT
CREATE OR REPLACE TEMPORARY TABLE MHS_ISAM_CUST_CNT AS 

SELECT  MHS_ISAM_CUST.TERR_GRP,
        COUNT(MHS_ISAM_CUST.CUST_ACCT_ID) AS CUST_CNT
FROM    MHS_ISAM_CUST
GROUP BY  MHS_ISAM_CUST.TERR_GRP;

USE ROLE SBX_EA_GENERAL_FR;
USE SECONDARY ROLE ALL;
--MHS ISAM GOALS & ACTUALS BY MONTH
CREATE OR REPLACE TEMPORARY TABLE MHS_ISAM_GOAL AS 

SELECT  PERIOD_END_DT, 
        MHS_ISAM_CUST.TERR_GRP,
        SUM(CASE WHEN MTRC_NAME IN ('NET SALES') THEN GOAL_VAL ELSE 0 END) AS NET_SALES_GOAL,
        NULL AS GROSS_PROFIT_GOAL,
        SUM(CASE WHEN MTRC_NAME IN ('NET SALES') THEN ACTLS_VAL ELSE 0 END) AS NET_SALES_ACTUAL,
        SUM(CASE WHEN MTRC_NAME IN ('GROSS PROFIT') THEN ACTLS_VAL ELSE 0 END) AS GROSS_PROFIT_ACTUAL,
        SUM(CASE WHEN MTRC_NAME IN ('AOP') THEN ACTLS_VAL ELSE 0 END) AS AOP_ACTUAL
FROM    PRD_PSAS_ANALYTICS_DB.GOLD_DP_SALESOPS.VW_ISAM_REP_ACCT_GOAL_ACTLS
JOIN    MHS_ISAM_CUST
ON      LTRIM(MHS_ISAM_CUST.CUST_ACCT_ID,'0') = LTRIM(VW_ISAM_REP_ACCT_GOAL_ACTLS.CUST_ACCT_ID,'0')
GROUP BY PERIOD_END_DT,
        MHS_ISAM_CUST.TERR_GRP;

        
--MHS ISAM FINAL RESULTS
CREATE OR REPLACE TEMPORARY TABLE MHS_ISAM_FINAL AS 
--SELECT * FROM MHS_ISAM_FINAL

SELECT  'MHS ISAM' TEAM,
        MHS_ISAM_GOAL.TERR_GRP,
        TO_CHAR(MHS_ISAM_GOAL.PERIOD_END_DT, 'YYYY-MM') AS YR_MONTH,
        MHS_ISAM_CUST_CNT.CUST_CNT,
        MHS_ISAM_GOAL.NET_SALES_GOAL,
        NULL AS GROSS_PROFIT_GOAL,
        MHS_ISAM_GOAL.NET_SALES_ACTUAL,
        MHS_ISAM_GOAL.GROSS_PROFIT_ACTUAL,
        MHS_ISAM_GOAL.AOP_ACTUAL
FROM    MHS_ISAM_GOAL
LEFT JOIN MHS_ISAM_CUST_CNT
ON        MHS_ISAM_GOAL.TERR_GRP = MHS_ISAM_CUST_CNT.TERR_GRP;



--CPH MPB PULL

CREATE OR REPLACE TEMPORARY TABLE SLS AS 

SELECT  YR_MTH, COUNT(DISTINCT CUST_ACCT_ID) CUST_CNT, SUM(NET_SLS) NET_SLS, SUM(GROSS_PROFIT) GP
FROM    SBX_PSAS_DB.SALES_OPS_GOV.MPB_NON_ACUTE_FY25_ACTUALS
JOIN    SBX_PSAS_DB.SALES_OPS_GOV.V_NON_ACUTE_COMMISSIONS_ADJ
ON      LTRIM(V_NON_ACUTE_COMMISSIONS_ADJ.CUSTOMER_ID,'0') = LTRIM(MPB_NON_ACUTE_FY25_ACTUALS.CUST_ACCT_ID,'0')
AND     V_NON_ACUTE_COMMISSIONS_ADJ.ASSIGNMENT1 in ('Christin Danker','Christina Kyzer','Jerry Taylor','Jessica Uldrick','Kara Wheeler');
GROUP BY  YR_MTH;

CREATE OR REPLACE TEMPORARY TABLE CUST_CNT AS 

SELECT  YR_MTH, COUNT(DISTINCT CUST_ACCT_ID) CUST_CNT
FROM    SBX_PSAS_DB.SALES_OPS_GOV.MPB_NON_ACUTE_FY25_ACTUALS
JOIN    SBX_PSAS_DB.SALES_OPS_GOV.V_NON_ACUTE_COMMISSIONS_ADJ
ON      LTRIM(V_NON_ACUTE_COMMISSIONS_ADJ.CUSTOMER_ID,'0') = LTRIM(MPB_NON_ACUTE_FY25_ACTUALS.CUST_ACCT_ID,'0')
AND     V_NON_ACUTE_COMMISSIONS_ADJ.ASSIGNMENT1 in ('Christin Danker','Christina Kyzer','Jerry Taylor','Jessica Uldrick','Kara Wheeler');


CREATE OR REPLACE TEMPORARY TABLE TARGET AS 

SELECT  YR_MTH, SUM(TARGET_NET_SALES) TARGET_NET_SALES, SUM(TARGET_GROSS_PROFIT) TARGET_GROSS_PROFIT
FROM    SBX_PSAS_DB.SALES_OPS_GOV.MPB_NON_ACUTE_FY25_TARGETS
JOIN    SBX_PSAS_DB.SALES_OPS_GOV.V_NON_ACUTE_COMMISSIONS_ADJ
ON      LTRIM(V_NON_ACUTE_COMMISSIONS_ADJ.CUSTOMER_ID,'0') = LTRIM(MPB_NON_ACUTE_FY25_TARGETS.CUST_ACCT_ID,'0')
WHERE    V_NON_ACUTE_COMMISSIONS_ADJ.ASSIGNMENT1 in ('Christin Danker','Christina Kyzer','Jerry Taylor','Jessica Uldrick','Kara Wheeler');
GROUP BY  YR_MTH;


--PROVIDER SOLUTIONS
CREATE OR REPLACE TEMPORARY TABLE PROVIDER_FINAL AS

SELECT  SEGMENT,
        'PROVIDER' AS TEAM,
        YR_MONTH,
        SUM(CUST_CNT) CUST_CNT,
        SUM(GROSS_PROFIT_GOAL) GROSS_PROFIT_GOAL,
        SUM(NET_SLS_GOAL) NET_SALES_GOAL,
        SUM(GROSS_PROFIT_ACTUAL) GROSS_PROFIT_ACTUAL,
        SUM(NET_SLS_ACTUAL) NET_SALES_ACTUAL
FROM    SBX_PSAS_DB.SALES_OPS_GOV.T_DATA_DEV_PROVIDER_INSIDE_SALES_SCORECARD
GROUP BY SEGMENT,
        YR_MONTH;


--CPH ISAM CUSTOMER COUNT
CREATE OR REPLACE TEMPORARY TABLE CPH_ISAM_CUST_CNT AS 

SELECT  COUNT(CUST_ACCT_ID) AS CUST_CNT
FROM    PRD_PSAS_ANALYTICS_DB.GOLD_CRM.VW_REP_HIERARCHY
WHERE   REP_GRP_NAME = 'INSIDE SALES TEAM'
AND     BUS_SGMNT = 'CPH'
AND     ROLE_TYPE = 'ISAM'
AND     CURRENT_RECORD_IND = 'Y';

--CPH ISAM GOALS & ACTUALS BY MONTH
CREATE OR REPLACE TEMPORARY TABLE ISAM_GOAL AS 

SELECT  PERIOD_END_DT,
        SUM(CASE WHEN MTRC_NAME = 'GROSS PROFIT' THEN GOAL_VAL ELSE 0 END) AS GROSS_PROFIT_GOAL,
        SUM(CASE WHEN MTRC_NAME = 'NET SALES' THEN ACTLS_VAL ELSE 0 END) AS NET_SLS_ACTUAL,
        SUM(CASE WHEN MTRC_NAME = 'GROSS PROFIT' THEN ACTLS_VAL ELSE 0 END) AS GROSS_PROFIT_ACTUAL,
        SUM(CASE WHEN MTRC_NAME = 'AOP' THEN ACTLS_VAL ELSE 0 END) AS AOP_ACTUAL
FROM    PRD_PSAS_ANALYTICS_DB.GOLD_DP_SALESOPS.VW_ISAM_REP_ACCT_GOAL_ACTLS
WHERE   BUS_SGMNT = 'CPH'
GROUP BY PERIOD_END_DT;


--CPH ISAM FINAL RESULTS
CREATE OR REPLACE TEMPORARY TABLE CPH_ISAM_FINAL AS 

SELECT  'CPH ISAM' TEAM,
        TO_CHAR(ISAM_GOAL.PERIOD_END_DT, 'YYYY-MM') AS YR_MONTH,
        CPH_ISAM_CUST_CNT.CUST_CNT,
        NULL NET_SLS_GOAL,
        ISAM_GOAL.GROSS_PROFIT_GOAL,
        ISAM_GOAL.NET_SLS_ACTUAL,
        ISAM_GOAL.GROSS_PROFIT_ACTUAL,
        ISAM_GOAL.AOP_ACTUAL
FROM    ISAM_GOAL
CROSS JOIN CPH_ISAM_CUST_CNT;
--SELECT * FROM CPH_ISAM_FINAL

